---
sidebar: sidebar 
permalink: xcp-nfs-add-ons.html 
keywords: xcp, nfs, hdfs, connector, configure, security 
summary: XCP NFS附加功能支援使用POSIX和HDFS連接器、增強安全性、並支援使用橫向擴充架構來加速資料移轉。 
---
= XCP NFS附加功能
:allow-uri-read: 


[role="lead"]
XCP NFS附加功能支援使用POSIX和HDFS連接器、增強安全性、並支援使用橫向擴充架構來加速資料移轉。



== NFSv4支援

當您只在資料中心的來源、目的地和目錄磁碟區上啟用NFSv4時、您可以使用POSIX路徑來移轉資料、而非匯出路徑。若要使用POSIX路徑、您必須先在執行XCP的主機系統上掛載來源、目的地及目錄磁碟區、然後使用POSIX檔案路徑來提供XCP的來源及目的地。請參閱 link:xcp-configure-posix-connector-nfs.html["設定POSIX連接器"]。

[NOTE]
====
* NFSv4支援僅限於POSIX路徑、而「複製」作業則不支援「同步」作業。
* 相較於XCP NFSv3 TCP通訊端用戶端引擎、POSIX連接器可能會變慢。


====


== POSIX連接器

XCP 支援使用 POSIX 連接器來提供資料移轉的來源、目的地和目錄路徑。POSIX 連接器（檔案： // ）可讓 XCP 存取任何 Linux 掛載的檔案系統、例如 NFSv4 、 XFS 和 Veritas 。對於非 root 使用者、系統管理員可以掛載檔案系統、讓任何非 root 使用者能夠使用含檔案： // 首碼的 POSIX 連接器來存取檔案系統。

當您沒有足夠的權限來掛載檔案、或資料中心的支援僅限於NFSv4時、您可以從使用POSIX連接器獲益。在這種情況下、任何root使用者都可以掛載來源和目的地、然後使用POSIX連接器存取路徑。使用POSIX連接器時、您只能執行「XCP複製」作業。



== XCP安全性

XCP安全功能可讓您在Linux主機上以非root使用者身分執行移轉。在較早的XCP版本中、以Linux機器上的root使用者身分執行移轉、並取得來源、目的地及目錄磁碟區的所有權限、而且會由XCP作業完成掛載。

當您準備資料移轉時、通常會關閉安全性、並讓系統管理員盡可能快速地複製所有內容。在使用XCP數年的正式作業環境中、持續進行轉換時、以系統管理員（或root）身分執行並不安全。因此、移除以root使用者身分執行XCP的需求、您就能在安全環境中使用XCP。當一般非root使用者執行XCP作業時、非root使用者的存取權限和限制與使用者相同。

在此安全環境中、root使用者可以在主機機器上掛載來源、目的地及目錄磁碟區、並為非root使用者提供寫入資料所需的目的地及目錄磁碟區權限。這可讓非root使用者使用XCP POSIX連接器功能執行移轉。



== XCP橫向擴充

直到現在為止、使用XCP的資料移轉僅限於具有較高RAM和CPU的單一主機。為了加快移轉速度、單一主機上的記憶體和核心都增加了、但複製PB資料仍可能需要相當長的時間。XCP橫向擴充架構可讓您使用多部主機來執行資料移轉。有了這項功能、您可以使用多部Linux主機來分散工作負載、並縮短移轉時間。

在單一系統效能不足的任何環境中、您都能從多節點橫向擴充中獲益。若要克服單一節點的效能限制、您可以使用單一「copy」（複製）（或「掃描-md5」）命令、在多個Linux系統或Hadoop叢集節點上執行工作人員。目前、XCP橫向擴充僅支援「複製」命令作業。



== Hadoop分散式檔案系統連接器

XCP支援將資料從Hadoop分散式檔案系統（HDFS）檔案系統移轉至NetApp檔案系統、反之亦然。在啟用安全性的Hadoop環境中、Hadoop叢集上的非root使用者可以執行移轉至NetApp NFSv4匯出檔案系統。HDFS連接器（HDFS：//）可讓XCP存取不同廠商所提供的任何HDFS檔案系統。非root使用者可使用XCP使用HDFS或POSIX連接器執行移轉。

您可以在XCP橫向擴充組態中納入HDFS叢集、因為它們使用多部高階Linux機器。如此可將額外XCP工作者節點的需求降至最低。對於資料移轉、您可以選擇重複使用HDFS叢集節點、或是使用不同的主機。


NOTE: HDFS連接器符合資格、可支援MapR和Cloudera叢集、但只能執行基礎「複製」作業。
