---
sidebar: sidebar 
permalink: xcp-install-file-analytics-for-nfs.html 
keywords: netapp, xcp, install, installing, file, analytics, nfs, upgrade, upgrading 
summary: 安裝或升級File Analytics for NFS 
---
= 安裝適用於NFS的檔案分析
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
安裝或升級File Analytics for NFS。

.關於這項工作
如需 NFS 的系統需求、請參閱 link:xcp-install-xcp-nfs.html["安裝XCP NFS"]。

。 `configure.sh` 指令碼會在 Red Hat Enterprise Linux （ RHEL ）主機機器上安裝 XCP File Analytics 。在安裝過程中、指令碼會在主機 Linux 機器上安裝 Postgres 資料庫、 Apache HTTPD 伺服器和其他必要的套件。如需特定支援 RHEL 版本的相關資訊、請參閱 link:https://mysupport.netapp.com/matrix/["IMT"^]。您可以視需要變更或更新至較新的版本、並遵守安全性準則。以深入瞭解 `configure.sh` 指令碼、執行 `./configure.sh -h` 在命令列上。

.開始之前
* 如果有任何 XCP 作業正在執行、 NetApp 建議您在開始設定之前先完成作業。
* 您的Linux機器必須連線至Yum儲存庫伺服器或網際網路。
* 如果在 Linux 機器上設定防火牆、您必須變更防火牆設定、以啟用 XCP 服務所使用的連接埠 5030 。


.步驟
. 安裝或升級File Analytics for NFS。
+
[role="tabbed-block"]
====
.安裝檔案分析
--
.. 瀏覽至 `xcp` 資料夾並執行 `./configure.sh` 指令碼：
+
如果安裝成功、則會顯示下列訊息：

+
[listing]
----
You can now access XCP file analytics using (<username>:<password>)
https://<ip_address>/xcp
----
+

NOTE: 您可以使用此使用者名稱和密碼登入 File Analytics GUI 。



--
.升級檔案分析
--
.. 瀏覽至 `xcp` 資料夾與執行 `./configure.sh -f`。
.. 在提示字元下輸入 `y` 以清理及重新設定系統。
+
指令碼核准後、它會清除現有的組態並重新設定系統。

+
如果成功、會顯示下列訊息：

+
[listing]
----
You can now access XCP file analytics using (<username>:<password>)
https://<ip_address>/xcp
----


--
====
. 在支援的瀏覽器中啟動檔案分析： * \https://<ip 位址： Linux/XCP* 。
+
請參閱 link:xcp-install-xcp-nfs.html["安裝XCP NFS"] 如需支援瀏覽器的相關資訊、


