---
sidebar: sidebar 
permalink: xcp-smb-reference-scan.html 
keywords: netapp, xcp, reference, smb, command, commands 
summary: XCP SMB 「掃描」命令參考資料 
---
= 掃描
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
中小企業 `scan` 命令會遞迴掃描整個 SMB 共用區、並在結束前列出所有檔案 `scan` 命令。

.語法
[source, cli]
----
xcp scan \\<SMB share path>
----
.顯示範例
[%collapsible]
====
[listing]
----
C:\Users\Administrator\Desktop\xcp>xcp scan \\<IP address or hostname of SMB server>\volxcp
c:\netapp\xcp\xcp scan \\<IP address of SMB destination server>\source_share
volxcp\3333.txt
volxcp\SMB.txt
volxcp\SMB1.txt
volxcp\com.txt
volxcp\commands.txt
volxcp\console.txt
volxcp\linux.txt
volxcp\net use.txt
volxcp\newcom.txt
volxcp\notepad.txt
c:\netapp\xcp\xcp scan \\<IP address of SMB destination server>\source_share
60,345 scanned, 0 matched, 0 errors
Total Time : 8s
STATUS : PASSED
C:\Users\Administrator\Desktop\xcp>Parameters
----
====
下表列出 `scan` 參數及其說明。

[cols="2*"]
|===
| 參數 | 說明 


| <<smb_scan_help,掃描 -h 、– help>> | 顯示如何使用掃描命令的詳細資訊。 


| <<掃描 -v>> | 增加除錯的詳細度。 


| <<smb_scan_parallel,掃描平行  ； n>  | 指定並行處理程序的數目（預設值： <cpu-count> ）。 


| <<smb_scan_match_filter,掃描 - 符合  ；篩選器 >  | 僅處理符合篩選條件的檔案和目錄。 


| <<smb_scan_exclude_filter,掃描 - 排除  ；篩選器 >  | 僅排除篩選器中的檔案和目錄。 


| <<掃描 -preserve-atime>> | 還原上次存取的來源日期。 


| <<smb_scan_depth,掃描深度  ； n>  | 將搜尋深度限制在 n 個層級。 


| <<掃描 - 統計資料>> | 以樹狀結構統計報告格式列出檔案。 


| <<掃描 -HTML>> | 以樹狀結構統計 HTML 報告格式列出檔案。 


| <<掃描 -csv>> | 以樹狀結構統計 CSV 報告格式列出檔案。 


| <<掃描 -l>> | 以長列表輸出格式列出檔案。 


| <<掃描擁有權>> | 擷取來源上檔案和目錄的擁有權資訊
系統。 


| <<掃描 -du>> | 摘要說明每個目錄（包括子目錄）的空間使用量。 


| <<smb_scan_fmt,掃描 -fmt ；運算式 >  | 根據 Python 運算式格式化檔案清單（請參閱 `xcp help -fmt` 以取得詳細資料）。 


| <<掃描廣告>> | 遞迴掃描整個 SMB 共用區、並列出所有檔案及任何相關的替代資料流。 
|===


== 掃描 -h 、– help

使用 `-h` 和 `–-help` 的參數 `scan` 命令顯示如何使用掃描命令的詳細資訊。

.語法
[source, cli]
----
xcp scan --help
----
.顯示範例
[%collapsible]
====
[listing]
----
C:\netapp\xcp>xcp scan --help

usage: xcp scan [-h] [-v] [-parallel <n>] [-match <filter>] [-exclude <filter>] [-preserve-atime] [-depth
<n>] [-loglevel <name>] [-stats] [-l] [-ownership] [-du]
                [-fmt <expression>] [-html] [-csv] [-edupe] [-bs <n>] [-ads]
                source
positional arguments:
   source
optional arguments:
   -h, --help           show this help message and exit
   -v                   increase debug verbosity
   -parallel <n>        number of concurrent processes (default: <cpu-count>)
   -match <filter>      only process files and directories that match the filter (see `xcp help -match` for     details)
   -exclude <filter>    Exclude files and directories that match the filter (see `xcp help -exclude` for details)
   -preserve-atime      restore last accessed date on source
   -depth <n>           limit the search depth
   -loglevel <name>     option to set log level filter (default:INFO)
   -stats               print tree statistics report
   -l                   detailed file listing output
   -ownership           retrieve ownership information
   -du                  summarize space usage of each directory including subdirectories
   -fmt <expression>    format file listing according to the python expression (see `xcp help -fmt` for details)
   -html                Save HTML statistics report
   -csv                 Save CSV statistics report
   -edupe               Include dedupe and sparse data estimate in reports (see documentation for details)
   -bs <n>              read/write block size for scans which read data with -edupe (default: 64k)
   -ads                 scan NTFS alternate data stream
----
====


== 掃描 -v

使用 `-v` 參數 `scan` 命令提供詳細的記錄資訊、以便在報告錯誤或警告時進行疑難排解或偵錯。

.語法
[source, cli]
----
xcp scan -v \\<IP address or hostname of SMB server>\source_share
----
.顯示範例
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp scan -v \\<IP address or hostname of SMB server>\source_share
xcp scan -v \\<IP address or hostname of SMB server>\source_share
---Truncated output----
source_share\ASUP.pm
source_share\ASUP_REST.pm
source_share\Allflavors_v2.pm
source_share\Armadillo.pm
source_share\AsupExtractor.pm
source_share\BTS_Config.pm
source_share\Backup.pm
source_share\Aggregate.pm
source_share\Burt.pm
source_share\CConfig.pm
source_share\CIFS.pm
source_share\CR.pm
source_share\CRC.pm
source_share\CSHM.pm
source_share\CSM.pm
source_share\agnostic\SFXOD.pm
source_share\agnostic\Snapmirror.pm
source_share\agnostic\VolEfficiency.pm
source_share\agnostic\flatfile.txt
source_share\agnostic
source_share
xcp scan \\<IP address or hostname of SMB server>\source_share
317 scanned, 0 matched, 0 errors
Total Time : 0s
STATUS : PASSED
----
====


== 掃描平行 <n>

使用 `-parallel <n>` 參數 `scan` 命令可設定較高或較低數量的 XCP 並行處理程序。


NOTE: n 的最大值為 61 。

.語法
[source, cli]
----
xcp scan -parallel <n> \\<IP address or hostname of SMB server>\source_share
----
.顯示範例
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp scan -parallel 8 \\<IP address or hostname of SMB server>\cifs_share
xcp scan -parallel 8 \\<IP address or hostname of SMB server>\cifs_share

cifs_share\ASUP.pm
cifs_share\ASUP_REST.pm
cifs_share\Allflavors_v2.pm
cifs_share\Armadillo.pm
cifs_share\AsupExtractor.pm
cifs_share\BTS_Config.pm
cifs_share\Backup.pm
cifs_share\Aggregate.pm
cifs_share\agnostic\CifsAccess.pm
cifs_share\agnostic\DU_Cmode.pm
cifs_share\agnostic\Flexclone.pm
cifs_share\agnostic\HyA_Clone_Utils.pm
cifs_share\agnostic\Fileclone.pm
cifs_share\agnostic\Jobs.pm
cifs_share\agnostic\License.pm
cifs_share\agnostic\Panamax_Clone_Utils.pm
cifs_share\agnostic\LunCmds.pm
cifs_share\agnostic\ProtocolAccess.pm
cifs_share\agnostic\Qtree.pm
cifs_share\agnostic\Quota.pm
cifs_share\agnostic\RbacCmdFetcher.pm
cifs_share\agnostic\RbacCmdFetcher_ReadMe
cifs_share\agnostic\SFXOD.pm
cifs_share\agnostic\Snapmirror.pm
cifs_share\agnostic\VolEfficiency.pm
cifs_share\agnostic\flatfile.txt
cifs_share\agnostic
cifs_share
xcp scan -parallel 8 \\<IP address or hostname of SMB server>\cifs_share
317 scanned, 0 matched, 0 errors
Total Time : 0s
STATUS : PASSED
----
====


== 掃描 - 比對 <filter>

使用 `-match <filter>` 參數 `scan` 僅處理符合篩選條件的檔案和目錄的命令。

.語法
[source, cli]
----
xcp scan -match <filter> \\<IP address or hostname of SMB server>\source_share
----
在下列範例中、 `scan -match` 掃描在一個月到一年之間變更的所有檔案、並針對找到的每個檔案、在主控台列印一行。會針對每個檔案傳回上次修改時間的 ISO 格式、人類可讀的檔案大小、檔案類型及其相對路徑。

.顯示範例
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp scan -match "1*month < modified < 1*year" -fmt "'{:>15} {:>7}{}
{}'.format(iso(mtime), humanize_size(size), type, relpath)" \\<IP address or hostname of SMB server>\source_share
xcp scan -match "1*month < modified < 1*year" -fmt "'{:>15} {:>7} {} {}'.format(iso(mtime), humanize_size(size), type, relpath)" \\<IP address or hostname of SMB server>\source_share

xcp scan -match 1*month < modified < 1*year -fmt '{:>15} {:>7} {} {}'.format(iso(mtime), humanize_size(size), type, relpath) \\<IP address or hostname of SMB server>\source_share
317 scanned, 0 matched, 0 errors
Total Time : 0s
STATUS : PASSED
----
====
在下列範例中、 `scan -match` 列出 3 個月以上未修改且大小大於 4 MB 的檔案。

.顯示範例
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp scan -match "modified > 3*month and size > 4194304" -fmt "'{},{},
{}'.format(iso(mtime), humanize_size(size), relpath)" \\<IP address or hostname of SMB
server>\source_share
xcp scan -match "modified > 3*month and size > 4194304" -fmt "'{}, {}, {}'.format(iso(mtime), humanize_size(size), relpath)" \\<IP address or hostname of SMB server>\source_share

xcp scan -match modified > 3*month and size > 4194304 -fmt '{}, {}, {}'.format(iso(mtime), humanize_size(size), relpath) \\<IP address or hostname of SMB server>\source_share
317 scanned, 0 matched, 0 errors
Total Time : 0s
STATUS : PASSED
----
====
下列兩個範例中的第一個僅符合目錄、格式化會在變數「 mtime 」、「 Relative path 」和「 depth 」之間新增一個逗號。

第二個範例會將相同的輸出重新導向至「 name.csv 」。

.顯示範例
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp scan -match "type is directory" -fmt "','.join(map(str, [iso(mtime), relpath, depth]))" \\<IP address or hostname of SMB server>\source_share
xcp scan -match "type is directory" -fmt "','.join(map(str, [iso(mtime), relpath, depth]))" \\<IP address or hostname of SMB server>\source_share

2013-03-07_15:41:40.376072,source_share\agnostic,1
2020-03-05_04:15:07.769268,source_share,0

xcp scan -match type is directory -fmt ','.join(map(str, [iso(mtime), relpath, depth])) \\<IP address or hostname of SMB server>\source_share
317 scanned, 2 matched, 0 errors
Total Time : 0s
STATUS : PASSED
----
====
.顯示範例
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp scan -match "type is directory" -fmt "','.join(map(str, [iso(mtime), relpath, depth]))" \\<IP address or hostname of SMB server>\source_share > name.csv
xcp scan -match "type is directory" -fmt "','.join(map(str, [iso(mtime), relpath, depth]))" \\<IP address or hostname of SMB server>\source_share > name.csv
----
====
下列範例會列印完整路徑和原始路徑 `mtime` 不是目錄的所有檔案的值。。 `mtime` 值會加上 70 個字元、以利提供可讀取的主控台報告。

.顯示範例
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp scan -match "type is not directory" -fmt "'{}{:>70}'.format(abspath, mtime)" \\<IP address or hostname of SMB server>\source_share
xcp scan -match "type is not directory" -fmt "'{} {:>70}'.format(abspath, mtime)" \\<IP address or hostname of SMB server>\source_share

--truncated output--
\\<IP address or hostname of SMB server>\source_share\ASUP.pm
1362688899.238098
\\<IP address or hostname of SMB server>\source_share\ASUP_REST.pm
1362688899.264073
\\<IP address or hostname of SMB server>\source_share\Allflavors_v2.pm
1362688899.394938
\\<IP address or hostname of SMB server>\source_share\Armadillo.pm
1362688899.402936
\\<IP address or hostname of SMB server>\source_share\AsupExtractor.pm
1362688899.410922
\\<IP address or hostname of SMB server>\source_share\BTS_Config.pm
1362688899.443902
\\<IP address or hostname of SMB server>\source_share\Backup.pm
1362688899.444905
\\<IP address or hostname of SMB server>\source_share\Aggregate.pm
1362688899.322019
\\<IP address or hostname of SMB server>\source_share\Burt.pm
1362688899.446889
\\<IP address or hostname of SMB server>\source_share\CConfig.pm
1362688899.4479
\\<IP address or hostname of SMB server>\source_share\CIFS.pm
1362688899.562795
\\<IP address or hostname of SMB server>\source_share\agnostic\ProtocolAccess.pm
1362688900.358093
\\<IP address or hostname of SMB server>\source_share\agnostic\Qtree.pm
1362688900.359095
\\<IP address or hostname of SMB server>\source_share\agnostic\Quota.pm
1362688900.360094
\\<IP address or hostname of SMB server>\source_share\agnostic\RbacCmdFetcher.pm
1362688900.3611
\\<IP address or hostname of SMB server>\source_share\agnostic\RbacCmdFetcher_ReadMe
1362688900.362094
\\<IP address or hostname of SMB server>\source_share\agnostic\SFXOD.pm
1362688900.363094
\\<IP address or hostname of SMB server>\source_share\agnostic\Snapmirror.pm
1362688900.364092
\\<IP address or hostname of SMB server>\source_share\agnostic\VolEfficiency.pm
1362688900.375077
\\<IP address or hostname of SMB server>\source_share\agnostic\flatfile.txt
1362688900.376076

xcp scan -match type is not directory -fmt '{} {:>70}'.format(abspath, mtime) \\<IP address or hostname of SMB server>\source_share
317 scanned, 315 matched, 0 errors
Total Time : 0s
STATUS : PASSED
----
====


== 掃描 - 排除 <filter>

使用 `-exclude <filter>` 使用 `scan` 根據篩選器中的模式排除目錄和檔案的命令。

.語法
[source, cli]
----
xcp scan -exclude <filter> \\<IP address or hostname of SMB server>\source_share
----
在下列範例中、 `scan -exclude` 排除在一個月到一年之間變更的任何檔案、並針對未排除的每個檔案、在主控台列印一行。針對每個檔案所列印的詳細資料為其上次修改時間的 ISO 格式、檔案的人類可讀大小、檔案類型及其相對路徑。

.顯示範例
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp scan -exclude "1*month < modified < 1*year" -fmt "'{:>15} {:>7}{}
{}'.format(iso(mtime), humanize_size(size), type, relpath)" \\<IP address or hostname ofSMB server>\localtest\arch\win32\agnostic
xcp scan -exclude "1*month < modified < 1*year" -fmt "'{:>15} {:>7} {}{}'.format(iso(mtime), humanize_size(size), type, relpath)" \\<IP address or hostname of SMB server>\localtest\arch\win32\agnostic
2013-03-07_15:39:22.852698 46 regular agnostic\P4ENV
2013-03-07_15:40:27.093887 8.40KiB regular agnostic\Client_outage.thpl
2013-03-07_15:40:38.381870 23.0KiB regular agnostic\IPv6_RA_Configuration_Of_LLA_In_SK_BSD.thpl
2013-03-07_15:40:38.382876 12.0KiB regular agnostic\IPv6_RA_Default_Route_changes.thpl
2013-03-07_15:40:38.383870 25.8KiB regular agnostic\IPv6_RA_Port_Role_Change.thpl
2013-03-07_15:40:38.385863 28.6KiB regular
agnostic\IPv6_RA_processing_And_Default_Route_Installation.thpl
2013-03-07_15:40:38.386865 21.8KiB regular agnostic\IPv6_RA_processing_large_No_Prefix.thpl
2013-03-07_15:40:40.323163          225 regular agnostic\Makefile
2013-03-07_15:40:40.324160          165 regular agnostic\Makefile.template
----truncated output ----
2013-03-07_15:45:36.668516            0 directory agnostic\tools\limits_finder\vendor\symfony\src
2013-03-07_15:45:36.668514            0 directory agnostic\tools\limits_finder\vendor\symfony
2013-03-07_15:45:40.782881            0 directory agnostic\tools\limits_finder\vendor
2013-03-07_15:45:40.992685            0 directory agnostic\tools\limits_finder
2013-03-07_15:45:53.242817            0 directory agnostic\tools
2013-03-07_15:46:11.334815            0 directory agnostic

xcp scan -exclude 1*month < modified < 1*year -fmt '{:>15} {:>7} {} {}'.format(iso(mtime), humanize_size(size), type, relpath) \\<IP address or hostname of SMB server>\localtest\arch\win32\agnostic
140,856 scanned, 1 excluded, 0 errors
Total Time : 46s
STATUS : PASSED
----
====
在下列範例中、 `scan -exclude` 列出未修改超過三個月且大小超過 5.5 KB 的未排除檔案。針對每個檔案所列印的詳細資料是其上次修改時間的 ISO 格式、檔案的人類可讀大小、檔案類型及其相對路徑。

.顯示範例
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp scan -exclude "modified > 3*month and size > 5650" -fmt "'{}, {}, {}'.format(iso(mtime), humanize_size(size), relpath)" \\<IP address or hostname of SMB server>\localtest\arch\win32\agnostic\snapmirror
xcp scan -exclude "modified > 3*month and size > 5650" -fmt "'{}, {}, {}'.format(iso(mtime), humanize_size(size) relpath)" \\<IP address or hostname of SMB server>\localtest\arch\win32\agnostic\snapmirror

2013-03-07_15:44:53.713279, 4.31KiB, snapmirror\rsm_abort.thpl
2013-03-07_15:44:53.714269, 3.80KiB, snapmirror\rsm_break.thpl
2013-03-07_15:44:53.715270, 3.99KiB, snapmirror\rsm_init.thpl
2013-03-07_15:44:53.716268, 2.41KiB, snapmirror\rsm_quiesce.thpl
2013-03-07_15:44:53.717263, 2.70KiB, snapmirror\rsm_release.thpl
2013-03-07_15:44:53.718260, 4.06KiB, snapmirror\rsm_resume.thpl
2013-03-07_15:44:53.720256, 4.77KiB, snapmirror\rsm_resync.thpl
2013-03-07_15:44:53.721258, 3.83KiB, snapmirror\rsm_update.thpl
2013-03-07_15:44:53.724256, 4.74KiB, snapmirror\sm_quiesce.thpl
2013-03-07_15:44:53.725254, 4.03KiB, snapmirror\sm_resync.thpl
2013-03-07_15:44:53.727249, 4.30KiB, snapmirror\sm_store_complete.thpl
2013-03-07_15:44:53.729250, 0, snapmirror

xcp scan -exclude modified > 3*month and size > 5650 -fmt '{}, {}, {}'.format(iso(mtime), humanize_size(size), relpath) \\<IP address or hostname of SMB server>\localtest\arch\win32\agnostic\snapmirror
18 scanned, 6 excluded, 0 errors Total Time : 0s
STATUS : PASSED
----
====
以下範例不包含目錄。它會列出未排除的檔案、其中的格式設定會在變數之間新增一個逗號 `mtime`、 `relpath`和 `depth`。

.顯示範例
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp scan -exclude "type is directory" -fmt "','.join(map(str, [iso(mtime), relpath, depth]))" \\<IP address or hostname of SMB server>\localtest\arch\win32\agnostic\snapmirror
xcp scan -exclude "type is directory" -fmt "','.join(map(str, [iso(mtime), relpath,depth]))"
\\<IP address or hostname of SMBserver>\localtest\arch\win32\agnostic\snapmirror
2013-03-07_15:44:53.712271,snapmirror\SMutils.pm,1
2013-03-07_15:44:53.713279,snapmirror\rsm_abort.pm,1
2013-03-07_15:44:53.714269,snapmirror\rsm_break.pm,1
2013-03-07_15:44:53.715270,snapmirror\rsm_init.thpl,1
2013-03-07_15:44:53.716268,snapmirror\rsm_quiesce.thpl,1
2013-03-07_15:44:53.717263,snapmirror\rsm_release.thpl,1
2013-03-07_15:44:53.718260,snapmirror\rsm_resume.thpl,1
2013-03-07_15:44:53.720256,snapmirror\rsm_resync.thpl,1
2013-03-07_15:44:53.721258,snapmirror\rsm_update.thpl,1
2013-03-07_15:44:53.722261,snapmirror\sm_init.thpl,1
2013-03-07_15:44:53.723257,snapmirror\sm_init_complete.thpl,1
2013-03-07_15:44:53.724256,snapmirror\sm_quiesce.thpl,1
2013-03-07_15:44:53.725254,snapmirror\sm_resync.thpl,1
2013-03-07_15:44:53.726250,snapmirror\sm_retrieve_complete.thpl,1
2013-03-07_15:44:53.727249,snapmirror\sm_store_complete.thpl,1
2013-03-07_15:44:53.728256,snapmirror\sm_update.thpl,1
2013-03-07_15:44:53.729260,snapmirror\sm_update_start.thpl,1

xcp scan -exclude type is directory -fmt ','.join(map(str, [iso(mtime), relpath, depth])) \\<IP address or hostname of SMB server>\localtest\arch\win32\agnostic\snapmirror
18 scanned, 1 excluded, 0 errors
Total Time : 0s
STATUS : PASSED
----
====
以下範例會列印完整的檔案路徑和原始檔案 `mtimevalue` 所有非目錄的檔案。。 `mtimevalue` 以 70 個字元填充、方便閱讀主控台報告。

.顯示範例
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp scan -exclude "type is not directory" -fmt "'{} {:>70}'.format(abspath, mtime)" \\<IP address or hostname of SMBserver>\source_share

xcp scan -exclude type is not directory -fmt '{} {:>70}'.format(abspath, mtime) \\<IP address or hostname of SMB server>\source_share
18 scanned, 17 excluded, 0errors
Total Time : 0s
STATUS : PASSED
----
====


== 掃描 -preserve-atime

使用 `-preserve-atime` 參數 `scan` 命令可還原來源上所有檔案的上次存取日期、然後重設 `atime` 到 XCP 讀取檔案之前的原始值。

掃描 SMB 共用時、檔案上的存取時間會修改（如果儲存系統設定為修改） `atime` 讀取時）、因為 XCP 正在逐一讀取檔案。XCP 永遠不會變更 `atime`只會讀取檔案、就會在其上觸發更新 `atime`。

.語法
[source, cli]
----
xcp scan -preserve-atime \\<IP address or hostname of SMB server>\source_share
----
.顯示範例
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp scan -preserve-atime \\<IP address or hostname of SMB server>\source_share
xcp scan -preserve-atime \\<IP address or hostname of SMB server>\source_share

source_share\ASUP.pm
source_share\ASUP_REST.pm
source_share\Allflavors_v2.pm
source_share\Armadillo.pm
source_share\AsupExtractor.pm
source_share\BTS_Config.pm
source_share\Backup.pm
source_share\Aggregate.pm
source_share\Burt.pm
source_share\CConfig.pm
source_share\agnostic\ProtocolAccess.pm
source_share\agnostic\Qtree.pm
source_share\agnostic\Quota.pm
source_share\agnostic\RbacCmdFetcher.pm
source_share\agnostic\RbacCmdFetcher_ReadMe
source_share\agnostic\SFXOD.pm
source_share\agnostic\Snapmirror.pm
source_share\agnostic\VolEfficiency.pm
source_share\agnostic\flatfile.txt
source_share\agnostic
source_share

xcp scan -preserve-atime \\<IP address or hostname of SMBserver>\source_share
317 scanned, 0 matched, 0 errors
Total Time : 1s
STATUS : PASSED
----
====


== 掃描深度 <n>

使用 `-depth <n>` 參數 `scan` 限制 SMB 共用目錄搜尋深度的命令。


NOTE: 。 `–depth` 選項指定 XCP 如何將檔案掃描至子目錄。

.語法
[source, cli]
----
xcp scan -depth <2> \\<IP address or hostname of SMB server>\source_share
----
.顯示範例
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp scan -depth 2 \\<IP address or hostname of SMB server>\source_share
xcp scan -depth 2 \\<IP address or hostname of SMB server>\source_share

source_share\ASUP.pm
source_share\ASUP_REST.pm
source_share\Allflavors_v2.pm
source_share\Armadillo.pm
source_share\AsupExtractor.pm
source_share\BTS_Config.pm
source_share\Backup.pm
source_share\Aggregate.pm
source_share\Burt.pm
source_share\CConfig.pm
source_share\CIFS.pm
source_share\CR.pm
source_share\CRC.pm
source_share\CSHM.pm
source_share\agnostic\Fileclone.pm
source_share\agnostic\Jobs.pm
source_share\agnostic\License.pm
source_share\agnostic\Panamax_Clone_Utils.pm
source_share\agnostic\LunCmds.pm
source_share\agnostic\ProtocolAccess.pm
source_share\agnostic\Qtree.pm
source_share\agnostic\Quota.pm
source_share\agnostic\RbacCmdFetcher.pm
source_share\agnostic\RbacCmdFetcher_ReadMe
source_share\agnostic\SFXOD.pm
source_share\agnostic\Snapmirror.pm
source_share\agnostic\VolEfficiency.pm
source_share\agnostic\flatfile.txt
source_share\agnostic
source_share

xcp scan -depth 2 \\<IP address or hostname of SMB server>\source_share
317 scanned, 0 matched, 0 errors
Total Time : 0s
STATUS : PASSED
----
====


== 掃描 - 統計資料

使用 `-stats` 參數 `scan` 以樹狀結構統計報告格式列出檔案的命令。


NOTE: stats 選項會將人類可讀的報告列印至主控台。其他報告格式選項為 -HTML 或 -csv.以逗號分隔的值（ CSV ）格式具有精確的值。如果目錄存在， CSV 和 HTML 報告會自動儲存在目錄中。

.語法
[source, cli]
----
xcp scan -stats \\<IP address or hostname of SMB server>\source_share
----
.顯示範例
[%collapsible]
====
[listing]
----
C:\netapp\xcp>xcp scan -stats \\<IP address or hostname of SMB server>\cifs_share

== Maximum Values ==
        Size      Depth      Namelen     Dirsize
     88.2MiB          3          108          20

== Average Values ==
        Size      Depth      Namelen    Dirsize
     4.74MiB          2          21            9

== Top File Extensions ==
no extension      .PDF       .exe       .html      .whl     .py      other
   22               2          2           2         2        1        9
  20.0KiB        1.54MiB    88.4MiB     124KiB    1.47MiB  1.62KiB   98.3MiB

== Number of files ==
  empty    <8KiB    8-64KiB    64KiB-1MiB    1-10MiB    10-100MiB    >100MiB
      2       24          2             7          2            3

== Space used ==
  empty    <8KiB    8-64KiB    64KiB-1MiB    1-10MiB    10-100MiB     >100MiB
      0  24.0KiB     124KiB       2.87MiB    2.91MiB       184MiB           0

== Directory entries ==
  empty     1-10     10-100        100-1K     1K-10K         >10K
               4          1
== Depth ==
    0-5     6-10      11-15         16-20     21-100         >100
     45

== Modified ==
>1 year  9-12 months  6-9 months  3-6 months  1-3 months  1-31 days  1-24 hrs  <1
hour     <15 mins       future      <1970       invalid
                                                                   44         1
                                                               190MiB

== Created ==
>1 year  9-12 months  6-9 months  3-6 months  1-3 months  1-31 days  1-24 hrs  <1
hour     <15 mins       future      <1970       invalid
                                                                   45
                                                               190MiB
Total count: 45
Directories: 5
Regular files: 40
Symbolic links:
Junctions:
Special files:
Total space for regular files: 190MiB
Total space for directories: 0
Total space used: 190MiB
Dedupe estimate: N/A
Sparse data: N/A
xcp scan -stats \\<IP address or hostname of SMB server>\cifs_share
45 scanned, 0 matched, 0 errors
Total Time : 0s
STATUS : PASSED
----
====


== 掃描 -HTML

使用 `-html` 參數 `scan` 列出 HTML 統計報告中檔案的命令。


NOTE: XCP 報告（ .csv 、 .html ）會儲存在 XCP 二進位檔案所在的相同位置。檔案名稱格式為 <xcp_process_id> <time_stamp> 。當 XCP 無法將安全性識別碼（ SID ）對應至擁有者名稱時、它會使用位於 SID 最後一個「–」之後的最後幾個數字來代表擁有者。例如、當 XCP 無法將 SID S-1-5-21-1896871423-3211229150-3383017265-4854184 對應至其擁有者時、它會使用 4854184 代表擁有者。

.語法
[source, cli]
----
xcp scan -stats -html -preserve-atime -ownership \\<IP address or hostname of SMB server>\source_share
----
.顯示範例
[%collapsible]
====
[listing]
----
Z:\scripts\xcp\windows>xcp scan -stats -html -preserve-atime -ownership \\<IP address or hostname of SMB server>\source_share
1,972 scanned, 0 matched, 0 errors, 7s
4,768 scanned, 0 matched, 0 errors,12s
7,963 scanned, 0 matched, 0 errors,17s
10,532 scanned, 0 matched, 0 errors,22s
12,866 scanned, 0 matched, 0 errors,27s
15,770 scanned, 0 matched, 0 errors,32s
17,676 scanned, 0 matched, 0 errors,37s

== Maximum Values ==
     Size      Depth     Namelen     Dirsize
   535KiB         16          33          45

== Average Values ==
     Size      Depth     Namelen     Dirsize
  10.3KiB          7          11           6

== Top File SIDs ==
S-1-5-21-1896871423-3211229150-3383017265-4854184 S-1-5-32-544 S-1-5-21-1896871423-3211229150-3383017265-3403389
     9318       8470           1

== Top Space SIDs ==
S-1-5-21-1896871423-3211229150-3383017265-4854184 S-1-5-32-544 S-1-5-21-1896871423-3211229150-3383017265-3403389
  76.8MiB    69.8MiB           0

== Top File Extensions ==
       py	      .rst	     .html  no	extension	    .txt	    .png	    other
     5418	      3738	      1974	         1197    	630      	336	      1344

== Number of files ==
    empty	     <8KiB	   8-64KiB	   64KiB-1MiB   1-10MiB	 10-100MiB	 >100MiB
      168	     11466	      2709	          294

== Space used ==
    empty     <8KiB      8-64KiB     64KiB-1MiB   1-10MiB  10-100MiB   >100MiB
        0     24.4MiB    55.3MiB        66.9MiB

== Directory entries ==
    empty      1-10       10-100         100-1K    1K-10K       >10K
       42      2690          420

== Depth ==
      0-5	     6-10	       11-15	          16-20	   21-100	      >100
     3832	    12527	        1424	              6

== Modified ==
  >1 year	  >1 month	  1-31 days	     1-24 hrs	  <1 hour	   <15 mins	  future	  invalid
  	11718       2961                                 3110
== Created ==
  >1 year  	>1 month    1-31 days	     1-24 hrs   <1 hour    <15 mins	  future	  invalid
                                              1    	17788
== Accessed ==
  >1 year 	>1 month	  1-31 days	     1-24 hrs	  <1 hour	   <15 mins	  future	  invalid
			                                              14624	       3165

Total count: 17789
Directories: 3152
Regular files: 14637
Symbolic links:
Junctions:
Special files:
Total space for regular files:147MiB
Total space for directories: 0
Total space used: 147MiB
Dedupe estimate: N/A
Sparse data: N/A
xcp scan -stats -html -preserve-atime -ownership \\<IP address or hostname ofSMB
server>\source_share
17,789 scanned, 0 matched, 0errors
Total Time : 39s
STATUS : PASSED
----
====


== 掃描 -csv

使用 `-csv` 參數 `scan` 用於列出 CSV 樹狀結構統計資料報告中檔案的命令。

.語法
[source, cli]
----
xcp scan -stats -csv -preserve-atime -ownership \\<IP address or hostname of SMB server>\source_share
----
.顯示範例
[%collapsible]
====
[listing]
----
Z:\scripts\xcp\windows>xcp scan -stats -csv -preserve-atime -ownership \\<IP address or hostname of SMB server>\source_share

1,761 scanned, 0 matched, 0 errors, 6s
4,949 scanned, 0 matched, 0 errors,11s
7,500 scanned, 0 matched, 0 errors,16s
10,175 scanned, 0 matched, 0 errors,21s
12,371 scanned, 0 matched, 0 errors,26s
15,330 scanned, 0 matched, 0 errors,31s
17,501 scanned, 0 matched, 0 errors,36s

== Maximum Values ==
    Size      Depth	     Namelen     Dirsize
  535KiB	       16	          33	        45

== Average Values ==
    Size	    Depth	     Namelen	   Dirsize
 10.3KiB	        7	          11	         6

== Top File SIDs ==
S-1-5-21-1896871423-3211229150-3383017265-4854184 S-1-5-32-544 S-1-5-21-1896871423-3211229150- 3383017265-3403389
    9318	     8470	           1

== Top Space SIDs ==
S-1-5-21-1896871423-3211229150-3383017265-4854184 S-1-5-32-544 S-1-5-21-1896871423-3211229150- 3383017265-3403389
 76.8MiB	  69.8MiB	           0

== Top File Extensions ==
	  .py	    .rst	   .html	no extension      .txt       .png	    other
	 5418	    3738	    1974          1197       630        336	     1344

==	Number of files ==
    empty      <8KiB	     8-64KiB    64KiB-1MiB	  1-10MiB	10-100MiB  	>100MiB
	  168	   11466	        2709           294

== Space used ==
   empty	   <8KiB	    8-64KiB    64KiB-1MiB	 1-10MiB	10-100MiB	  >100MiB
      0	     24.4MiB        55.3MiB	      66.9MiB	       0          0         0

== Directory entries ==
	empty	     1-10	  10-100        100-1K    1K-10K       >10K
	   42	     2690	     420

==	Depth ==
	  0-5	     6-10	   11-15	       16-20	  21-100       >100
	 3832	    12527	    1424             6

==	Modified ==
 >1 year	 >1 month   1-31 days	 1-24 hrs  	<1 hour  	<15 mins	future	invalid
	 11718	     2961		             3110

== Created ==
 >1 year	 >1 month   1-31 days	 1-24 hrs  	<1 hour	  <15 mins	future	invalid
                                        17789

== Accessed ==
 >1 year	 >1 month   1-31 days	 1-24 hrs	  <1 hour	  <15 mins	future	invalid
		                                15754	     2035

Total count: 17789
Directories: 3152
Regular files: 14637 Symbolic links:
Junctions:
Special files:
Total space for regular files: 147MiB Total space for directories: 0 Total space used: 147MiB
Dedupe estimate: N/A Sparse data: N/A
xcp scan -stats -csv -preserve-atime -ownership \\<IP address or hostname of SMB server>\source_share
17,789 scanned, 0 matched, 0 errors Total Time : 40s
STATUS : PASSED
----
====


== 掃描 -l

使用 `-l` 參數 `scan` 以長清單輸出格式列出檔案的命令。

.語法
[source, cli]
----
xcp scan -l \\<IP address or hostname of SMB server>\source_share
----
.顯示範例
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp scan -l \\<IP address or hostname of SMB server>\source_share xcp scan -l \\<IP address or hostname of SMB server>\source_share

f   195KiB   7y0d source_share\ASUP.pm
f  34.7KiB   7y0d source_share\ASUP_REST.pm
f  4.11KiB	 7y0d source_share\Allflavors_v2.pm
f  38.1KiB	 7y0d source_share\Armadillo.pm
f  3.83KiB	 7y0d source_share\AsupExtractor.pm
f  70.1KiB	 7y0d source_share\BTS_Config.pm
f  2.65KiB	 7y0d source_share\Backup.pm
f  60.3KiB	 7y0d source_share\Aggregate.pm
f  36.9KiB	 7y0d source_share\Burt.pm
f  8.98KiB	 7y0d source_share\CConfig.pm
f  19.3KiB 	 7y0d source_share\CIFS.pm
f  20.7KiB	 7y0d source_share\CR.pm
f  2.28KiB   7y0d source_share\CRC.pm
f  18.7KiB   7y0d source_share\CSHM.pm
f  43.0KiB   7y0d source_share\CSM.pm
f  19.7KiB	 7y0d source_share\ChangeModel.pm
f  33.3KiB	 7y0d source_share\Checker.pm
f  3.47KiB	 7y0d source_share\Class.pm
f  37.8KiB	 7y0d source_share\Client.pm
f   188KiB   7y0d source_share\agnostic\Flexclone.pm
f  15.9KiB   7y0d source_share\agnostic\HyA_Clone_Utils.pm
f  13.4KiB   7y0d source_share\agnostic\Fileclone.pm
f  41.8KiB   7y0d source_share\agnostic\Jobs.pm
f  24.0KiB   7y0d source_share\agnostic\License.pm
f  34.8KiB   7y0d source_share\agnostic\Panamax_Clone_Utils.pm
f  30.2KiB   7y0d source_share\agnostic\LunCmds.pm
f  40.9KiB   7y0d source_share\agnostic\ProtocolAccess.pm
f  15.7KiB   7y0d source_share\agnostic\Qtree.pm
f  29.3KiB   7y0d source_share\agnostic\Quota.pm
f  13.7KiB   7y0d source_share\agnostic\RbacCmdFetcher.pm
f  5.55KiB   7y0d source_share\agnostic\RbacCmdFetcher_ReadMe
f  3.92KiB   7y0d source_share\agnostic\SFXOD.pm
f  35.8KiB   7y0d source_share\agnostic\Snapmirror.pm
f  40.4KiB   7y0d source_share\agnostic\VolEfficiency.pm
f  6.22KiB   7y0d source_share\agnostic\flatfile.txt
d	     0   7y0d source_share\agnostic
d	     0 19h17m source_share

xcp scan -l \\<IP address or hostname of SMB server>\source_share
317 scanned, 0 matched, 0 errors
Total Time : 0s
STATUS : PASSED
----
====


== 掃描擁有權

使用 `-ownership` 參數 `scan` 擷取檔案所有權資訊的命令。


NOTE: 您只能使用 `-ownership` 使用 `-l`、 `-match`、 `-fmt`或 `-stats` 參數。

.語法
[source, cli]
----
xcp scan -l -ownership \\<IP address or hostname of SMB server>\source_share
----
.顯示範例
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp scan -l -ownership \\<IP address or hostname of SMB server>\source_share xcp scan -l -ownership \\<IP address or hostname of SMB server>\source_share

f	BUILTIN\Administrators	195KiB	7y0d	source_share\ASUP.pm
f	BUILTIN\Administrators	34.7KiB	7y0d	source_share\ASUP_REST.pm
f	BUILTIN\Administrators	4.11KiB	7y0d	source_share\Allflavors_v2.pm
f	BUILTIN\Administrators	38.1KiB	7y0d	source_share\Armadillo.pm
f	BUILTIN\Administrators	3.83KiB	7y0d	source_share\AsupExtractor.pm
f	BUILTIN\Administrators	70.1KiB	7y0d	source_share\BTS_Config.pm
f	BUILTIN\Administrators	2.65KiB	7y0d	source_share\Backup.pm
f	BUILTIN\Administrators	60.3KiB	7y0d	source_share\Aggregate.pm
f	BUILTIN\Administrators	36.9KiB	7y0d	source_share\Burt.pm
f	BUILTIN\Administrators	8.98KiB	7y0d	source_share\CConfig.pm
f	BUILTIN\Administrators	19.3KiB	7y0d	source_share\CIFS.pm
f	BUILTIN\Administrators	20.7KiB	7y0d	source_share\CR.pm
f	BUILTIN\Administrators	2.28KiB	7y0d	source_share\CRC.pm
f	BUILTIN\Administrators	18.7KiB	7y0d	source_share\CSHM.pm
f	BUILTIN\Administrators	43.0KiB	7y0d	source_share\CSM.pm
f	BUILTIN\Administrators	19.7KiB	7y0d	source_share\ChangeModel.pm
f	BUILTIN\Administrators	33.3KiB	7y0d	source_share\Checker.pm
f	BUILTIN\Administrators	3.47KiB	7y0d	source_share\Class.pm
f	BUILTIN\Administrators	37.8KiB	7y0d	source_share\Client.pm
f	BUILTIN\Administrators	2.44KiB	7y0d	source_share\ClientInfo.pm
f	BUILTIN\Administrators	37.2KiB	7y0d	source_share\ClientMgr.pm
f	BUILTIN\Administrators	17.1KiB	7y0d	source_share\ClientRPC.pm
f	BUILTIN\Administrators	9.21KiB	7y0d	source_share\ClusterAgent.pm
f   BUILTIN\Administrators  15.7KiB 7y0d source_share\agnostic\Qtree.pm
f   BUILTIN\Administrators  29.3KiB 7y0d source_share\agnostic\Quota.pm
f   BUILTIN\Administrators  13.7KiB 7y0d source_share\agnostic\RbacCmdFetcher.pm
f   BUILTIN\Administrators  5.55KiB 7y0d source_share\agnostic\RbacCmdFetcher_ReadMe
f   BUILTIN\Administrators  3.92KiB 7y0d source_share\agnostic\SFXOD.pm
f   BUILTIN\Administrators  35.8KiB 7y0d source_share\agnostic\Snapmirror.pm
f   BUILTIN\Administrators  40.4KiB 7y0d source_share\agnostic\VolEfficiency.pm
f   BUILTIN\Administrators  6.22KiB 7y0d source_share\agnostic\flatfile.txt
d   BUILTIN\Administrators  7y0d source_share\agnostic
d   BUILTIN\Administrators

xcp scan -l -ownership \\<IP address or hostname of SMB server>\source_share
317 scanned, 0 matched, 0 errors Total Time : 1s
STATUS : PASSED
----
====


== 掃描 -du

使用 `-du` 參數 `scan` 用於總結每個目錄（包括子目錄）的空間使用情況的命令。

.語法
[source, cli]
----
xcp scan -du \\<IP address or hostname of SMB server>\source_share
----
.顯示範例
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp scan -du \\<IP address or hostname of SMB server>\source_share xcp scan -du \\<IP address or hostname of SMB server>\source_share

  569KiB source_share\agnostic
  19.8MiB source_share

xcp scan -du \\<IP address or hostname of SMB server>\source_share
317 scanned, 0 matched, 0 errors
Total Time : 0s
STATUS : PASSED
----
====


== 掃描 -fmt <expression>

使用 `-fmt <expression>` 參數 `scan` 根據定義的運算式格式化檔案清單的命令。

.語法
[source, cli]
----
xcp scan -fmt "', '.join(map(str, [relpath, name, size, depth]))" \\<IPaddress or hostname of SMB server>\source_share
----
.顯示範例
[%collapsible]
====
[listing]
----
c:\netapp\xcp>xcp scan -fmt "', '.join(map(str, [relpath, name, size, depth]))"	\\<IP address or hostname of SMB server>\source_share
xcp scan -fmt "', '.join(map(str, [relpath, name, size, depth]))"	\\<IP address or hostname of SMB server>\source_share

source_share\ASUP.pm, ASUP.pm, 199239, 1
source_share\ASUP_REST.pm, ASUP_REST.pm, 35506, 1
source_share\Allflavors_v2.pm, Allflavors_v2.pm, 4204, 1
source_share\Armadillo.pm, Armadillo.pm, 39024, 1
source_share\AsupExtractor.pm, AsupExtractor.pm, 3924, 1
source_share\BTS_Config.pm, BTS_Config.pm, 71777, 1
source_share\Backup.pm, Backup.pm, 2714, 1
source_share\Aggregate.pm, Aggregate.pm, 61699, 1
source_share\Burt.pm, Burt.pm, 37780, 1
source_share\CConfig.pm, CConfig.pm, 9195, 1
source_share\CIFS.pm, CIFS.pm, 19779, 1
source_share\CR.pm, CR.pm, 21215, 1
source_share\CRC.pm, CRC.pm, 2337, 1
source_share\agnostic\LunCmds.pm, LunCmds.pm, 30962, 2
source_share\agnostic\ProtocolAccess.pm, ProtocolAccess.pm, 41868, 2
source_share\agnostic\Qtree.pm, Qtree.pm, 16057,2
source_share\agnostic\Quota.pm, Quota.pm, 30018,2
source_share\agnostic\RbacCmdFetcher.pm, RbacCmdFetcher.pm, 14067, 2
source_share\agnostic\RbacCmdFetcher_ReadMe, RbacCmdFetcher_ReadMe, 5685, 2
source_share\agnostic\SFXOD.pm, SFXOD.pm, 4019, 2
source_share\agnostic\Snapmirror.pm, Snapmirror.pm, 36624, 2
source_share\agnostic\VolEfficiency.pm, VolEfficiency.pm, 41344, 2
source_share\agnostic\flatfile.txt, flatfile.txt, 6366, 2
source_share\agnostic, agnostic, 0, 1
source_share, , 0, 0
xcp scan -fmt ', '.join(map(str, [relpath, name, size, depth])) \\<IP address or hostname of SMB server>\source_share
317 scanned, 0 matched, 0 errors
Total Time : 0s
STATUS : PASSED
----
====


== 掃描廣告

使用 `-ads` 使用標記參數 `scan` 命令以遞迴方式掃描整個 SMB 共用區、並列出所有檔案及任何相關的替代資料流。

.語法
[source, cli]
----
xcp scan -ads \\<source_ip_address>\source_share\src
----
.顯示範例
[%collapsible]
====
[listing]
----
C:\netapp\xcp>xcp scan -ads \\<source_ip_address>\source_share\src

src\file1.txt:ads1
src\file1.txt:ads_file1.txt_1697037934.4154522.txt
src\file1.txt
src\file2.txt:ads1
src\file2.txt:ads_file2.txt_1697037934.5873265.txt
src\file2.txt
src\test1.txt:ads_test1.txt_1697037934.7435765.txt
src\test1.txt
src\dir1\dfile1.txt:ads1
src\dir1\dfile1.txt:ads_dfile1.txt_1697037934.1185782.txt
src\dir1\dfile1.txt:ads_xcp.exe
src\dir1\dfile1.txt:ads_tar
src\dir1\dfile1.txt:java_exe
src\dir1\dfile1.txt:cmdzip
src\dir1\dfile1.txt:ads1_2GB
src\dir1\dfile1.txt
src\dir1:ads1
src\dir1:ads_dir1_1697038504.087317.txt
src\dir1
src:ads_src_1697038504.7123322.txt
src

xcp scan -ads \\<source_ip_address>\source_share\src
6 scanned, 0 matched, 0 errors, 15 ads scanned
Total Time : 2s
STATUS : PASSED
----
====