---
sidebar: sidebar 
permalink: xcp-configure-multinode-scaleout-nfs.html 
keywords: xcp, configure, nfs, multinode, scale, out 
summary: 若要克服單一節點的效能限制、您可以使用單一XCP copy命令、在多個Linux系統或叢集節點上執行工作人員。 
---
= 設定多節點橫向擴充
:allow-uri-read: 


[role="lead"]
對於XCP NFS、您可以使用單一「copy」（複製）（或「shcan -md5」）命令、在多個Linux系統或叢集節點上執行工作人員、藉此克服單一節點的效能限制。

在單一系統效能不足的任何環境中、例如在下列情況下、多節點橫向擴充都很有幫助：

* 當單一節點複製PB資料需要數月時間時
* 當高延遲連線至雲端物件存放區時、個別節點的速度會變慢
* 在執行大量I/O作業的大型HDFS叢集伺服器陣列中


多節點橫向擴充的路徑語法為：節點worker1、worker2、worker3。

請考慮設定四台Linux主機、其CPU和RAM組態類似。您可以使用全部四個主機進行移轉、因為XCP可以協調所有主機節點的複本作業。若要在橫向擴充環境中使用這些節點、您必須將四個節點中的一個識別為主節點、而其他節點識別為工作節點。例如、對於Linux四節點設定、請將節點命名為「master」、「worker1」、「worker2」和「worker3」、然後在主節點上設定組態：

. 將XCP複製到主目錄。
. 安裝並啟動XCP授權。
. 修改「xcp.ini`」檔案並新增目錄路徑。
. 從主節點將無密碼的安全Shell（SSH）設定為工作節點：
+
.. 在主節點上產生金鑰：
+
「sh-keygen-b 2048-t ra -f / root/.ssh / id_ra -q -N ''」

.. 將金鑰複製到所有工作節點：
+
「sh-copy -id -i /root/.ssh / id_ras.pub root@worker1」





XCP主節點使用SSH在其他節點上執行工作人員。您必須設定工作節點、為在主節點上執行XCP的使用者啟用無密碼SSH存取。例如、若要讓主節點上的使用者示範使用節點「worker1」做為XCP工作者節點、您必須將XCP二進位檔從主節點複製到主目錄中的所有工作節點。

當您同時啟動多個XCP工作者時、為了避免錯誤、您應該增加每個工作者節點上的「shd MaxStartups」參數、如下列範例所示：

[listing]
----
echo "MaxStartups 100" | sudo tee -a /etc/ssh/sshd_config sudo systemctl
restart sshd
----
當XCP在叢集節點上執行工作者時、工作者處理序會從主節點上的主要XCP處理序繼承環境變數。若要自訂特定的節點環境、您必須在「nodes.ini`」檔案中設定變數、該檔案僅位於主節點的組態目錄（工作節點沒有組態目錄或目錄）。例如、在不同位置的Ubuntu伺服器mars（如Wave（即CentOS）中、其「libjvm.so」位於主節點的不同位置、則需要一個組態目錄、才能讓Mars上的員工使用HDFS連接器。以下範例顯示此設定：

[listing]
----
[schay@wave ~]$ cat /opt/NetApp/xFiles/xcp/nodes.ini [mars]
NHDFS_LIBJVM_PATH=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/
amd64/server/libjvm.so
----
如果您使用具有POSIX和HDFS檔案路徑的多工作階段、則必須在主節點和所有工作節點上掛載檔案系統、以及來源和目的地匯出的檔案系統。

當XCP在工作節點上執行時、工作節點沒有本機組態（無授權、記錄檔或目錄）。您的主目錄中的系統僅需要XCP二進位。例如、若要執行「copy」命令、主要節點和所有工作節點都需要存取來源和目的地。對於「XCP copy（XCP複製）-節點LINKX1、linu2 HDFS：//user/demo/test \file//mnt/ontap'、「LINKuX1」和「linux2」主機、必須設定HDFS用戶端軟體、並將NFS匯出掛載於/mnt/ONTAP、如前所述、將XCP複本放在主目錄的二進位目錄中。

您可以搭配使用POSIX和HDFS連接器、多節點橫向擴充和安全功能。例如、下列「複製」和「驗證」命令將POSIX和HDFS連接器與安全性和橫向擴充功能結合在一起：

* 「copy（複製）”命令範例：
+
[listing]
----
./xcp copy hdfs:///user/demo/d1 file:///mnt/nfs-server0/d3
./xcp copy -match "'USER1 in name'" file:///mnt/nfs-server0/d3
hdfs:///user/demo/d1
./xcp copy —node worker1,worker2,worker3 hdfs:///user/demo/d1
file:///mnt/nfs-server0/d3
----
* 「驗證’命令範例：


[listing]
----
./xcp verify hdfs:///user/demo/d2 file:///mnt/nfs-server0/d3
----