---
sidebar: sidebar 
permalink: xcp-migrate-data.html 
keywords: netapp, xcp, migrate, data, nfs, smb, copy, resume, sync, verify 
summary: 移轉資料 
---
= 移轉NFS資料
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用規劃移轉之後 `show` 和 `scan` 命令、您可以移轉 NFS 資料。



== 複本

「copy」命令會掃描整個來源目錄結構、並將其複製到目的地NFSv3匯出。「copy」命令需要將來源和目的地路徑做為變數。掃描與複製的檔案、處理量/速度和經過時間詳細資料會顯示在複製作業結束時。

*範例：*

[listing]
----
xcp copy <source_nfs_export_path> <destination_nfs_export_path>
----
* POSIX路徑範例：*

[listing]
----
xcp copy -newid <id> file:///mnt/source file:///mnt/dest
----
執行 `xcp help copy` 以取得更多詳細資料。



== 繼續

「假定」命令會指定目錄索引名稱或編號、重新啟動先前中斷的複製作業。上一個複製作業的目錄索引名稱或編號會儲存在「目錄路徑」：/型 錄/索引目錄中。

*範例：*

[listing]
----
xcp resume -id <catalog_name>
----
執行 `xcp help resume` 以取得更多詳細資料。



== 同步

「sync」命令會使用目錄索引標籤名稱或先前複製作業的編號、掃描來源NFS目錄上所執行的變更和修改。來源遞增變更會複製並套用至目標目錄。舊的目錄索引編號會在同步operation#之後以新的[.Underlines]#取代。

*範例：*

[listing]
----
xcp sync -id <catalog_name>
----
執行 `xcp help sync` 以取得更多詳細資料。



== 驗證

在複製作業之後、「驗證」命令會在來源目錄和目標目錄之間使用逐位元組的完整資料比較、而不使用目錄索引編號。此命令會檢查修改時間及其他檔案或目錄屬性、包括權限。命令也會讀取兩側的檔案、並比較資料。

*範例：*

[listing]
----
xcp verify <source_ip_address>:/source_vol <destination_ip_address>:/dest_vol
----
* POSIX路徑範例：*

[listing]
----
xcp verify file:///mnt/source file:///mnt/dest
----
執行 `xcp help verify` 以取得更多詳細資料。



== iSync

。 `isync` 命令會比較來源和目的地、並在不使用目錄索引的情況下同步目標上的差異。

* 範例 *

[listing]
----
xcp isync <source_ip_address>:/src <destination_ip_address>:/dest

----
您可以使用 `isync` 使用 `estimate` 預估所需時間的選項 `isync` 同步遞增變更的命令。。 `-id` 參數指定先前複本作業的目錄名稱。


NOTE: 如果您變更的資料集大小超過使用的資料集大小的 25% 、則會變更 `isync estimate` 命令可能不會顯示預期的結果。

* 範例 *

[listing]
----
xcp isync estimate -id <name>
----
執行 `xcp help isync` 以取得更多詳細資料。
