---
sidebar: sidebar 
permalink: xcp-migrate-nfs-additional-features.html 
keywords: xcp, nfs, chomod, chown, posix, ownership, change, file, path, directory, command, scan 
summary: XCP包含一些額外的NFS功能、可讓您輕鬆變更任何NFS共用區或POSIX路徑的檔案和目錄擁有權和權限。 
---
= 其他NFS功能
:allow-uri-read: 


[role="lead"]
XCP包含一些額外的NFS功能。



== chown和chmod

您可以使用XCP「chown」和「chmod」命令、以遞歸方式變更指定NFS共用區或POSIX路徑的所有檔案和目錄。如此可提升數百萬個檔案的效能。


NOTE: 在變更檔案的擁有權之前、您必須先設定新的擁有者。否則、命令將會失敗。XCP「chown」和「chmod」命令的運作方式類似於Linux「chown」和「chmod」命令。



=== chmod

"chmod"命令會掃描並變更所選目錄結構中所有檔案的檔案權限。"chmod"命令需要一個模式或參照、以及NFS共用區或POSIX路徑做為變數。XCP「chmod」會以遞迴方式變更指定路徑的權限。您可以使用「chmod」命令來顯示掃描的檔案總數、以及輸出中已變更的權限。

*範例：*

....
xcp chmod -mode 777 NFS [server:/export path | file://<NFS mounted path>]
xcp chmod -mode 707 nfs_server01.netapp.com:/export1
xcp chmod -reference nfs_server01.netapp.com:/export/dir1/file.txt  nfs_server02.netapp.com: export1
xcp chmod -match “fnm(‘file.txt’)” -mode 111 file:///mnt/nfs_mount_point/
xcp chmod -exclude “fnm(‘file.txt’)” -mode 111 file:///demo/user1/
....
如需詳細資訊、請執行「XCP說明chmod」命令。



=== chown

您可以使用XCP「chown」命令、以遞歸方式變更指定NFS共用區或POSIX路徑的所有檔案和目錄。如此可提升數百萬個檔案的效能。

「chown」命令會掃描並變更所選目錄結構中所有檔案的擁有權。「chown」命令需要NFS共用區或POSIX路徑做為變數。XCP「chown」會以遞迴方式變更指定路徑的擁有權。

* 範例 *

....
xcp chown -user user1 NFS [server:/export path | file://<NFS mounted path>
xcp chown -user user1 nfs_server01.netapp.com:/export1
xcp chown -user user1 -group group1 nfs_server01.netapp.com:/export1/dir1/
xcp chown  -reference nfs_server01.netapp.com:/export/dir1/file.txt  nfs_server02.netapp.com:/export1
xcp chown -match “fnm(‘file.txt’)” -user user1 file:///mnt/nfs_mount_point/
xcp chown -exclude “fnm(‘file.txt’)” -user user1 -group group1
xcp chown -user-from user1 -user user2 file:///mnt/nfs_mount_point/
xcp chown -group-from group1 -group group2 nfs_server01.netapp.com:/export1/
....
如需詳細資訊、請執行「XCP說明chown」命令。



== XCP 預估

XCP 預估功能可預估完成基準的時間 `copy` 從來源到目的地的作業。它會計算完成基準的預估時間 `copy` 使用所有目前可用的系統資源（例如 CPU 、 RAM 、網路或其他參數）來執行作業。當您使用時 `-target` 選項： XCP 會執行範例複本作業、以找出預估時間。

* 範例 *

....
server : NFS server IP
export : NFS exported path for the above IP

xcp static estimation
xcp estimate -id <scan id>

xcp live estimation with default time
xcp estimate -id <scan id> -target server:/export

xcp live estimation with -t option
xcp estimate -id <scan id> -t <time for which estimation should run> -target server:/export
....


== 索引刪除

您可以使用 `indexdelete` 刪除目錄索引的命令。

* 範例 *

[listing]
----
xcp indexdelete
----
執行 `xcp help indexdelete` 以取得更多詳細資料。
